### ISSUE TITLE
Create a ticket on Prism Launcher for the Java 17 compatibility check

### ISSUE THREAD

**Issue by telvarost** [telvarost/AnnoyanceFix-StationAPI#30]
Its possible that this could be a ticket for StationAPI or Babric instead.
We should look into it at some point.

**Comment by 2zqa** [comment]
We should test whether the issue also appears when not using our mod, and then whether it appears when running Babric alone (i.e. disabling StationAPI as well). That way we can deduce with certainty who is at fault.

I assume this is a StationAPI issue, since I believe to recall the Babric Edition of AnnoyanceFix runs just fine.

**Comment by telvarost** [comment]
MiTask has this fixed in his fork of the babric prism-launcher

**Comment by telvarost** [comment]
We can close this when his fix gets merged:https://github.com/babric/prism-instance/pull/1

**Comment by MrMasrozYTLIVE** [comment]
@telvarost it is fixed. Close this issue

**Comment by telvarost** [comment]
It is fixed, although they haven't made a release with the fix version yet. But, since I am pointing people to my release version of the instance that is built with the fix, you are correct I believe this issue can be closed now.
Hopefully 6pak creates a real release eventually: https://github.com/telvarost/prism-instance/releases
